INSERT INTO user VALUES(1,'$2a$04$2/y1i84w03REpz.t1nTaYeFsgwaK7FnYnEwdEVLX79cQjHvOglg4u','username')
INSERT INTO customer VALUES(1,'user1',null,'Miguel','www.imageshare.com/userid/102/photo','Pérez')
INSERT INTO customer VALUES(2,'user1',null,'Alberto','www.imageshare.com/userid/112/photo','Rodríguez')
INSERT INTO roles VALUES(1,'ROLE_ADMIN')
INSERT INTO roles VALUES(2,'ROLE_USER')
INSERT INTO user_roles VALUES(1,1)
INSERT INTO user_roles VALUES(1,2)